[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pipeGEM"
version = "0.2.0"
description = "Processing and integrating data with genome-scale metabolic models (GEM)"
readme = "README.md"
authors = [{ name = "Yu-Te Lin", email = "qwerty239qwe@gmail.com" }]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
keywords = ["metabolism", "metabolic-model", "computational-biology", "system-biology", "cobra"]
dependencies = [
    "cobra",
    "pandas",
    "numpy",
    "scipy",
    "matplotlib",
    "requests",
    "scikit-learn",
    "scikit-posthocs",
    "seaborn",
    "umap-learn>=0.5.6",
    "numba>=0.59; python_version >= '3.10' and python_version < '3.13'",
    "numba>=0.63; python_version >= '3.13'",
    "biodbs",
    "tqdm",
    "optlang",
    "networkx",
    "zeep",
    "pint",
    "pingouin",
    "scanpy",
    "tomlkit",
    "dask[distributed]",
    "openpyxl"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pip-tools",
    "pytest",
    "flake8",
    "pytest-cov>=4.0.0",
]
doc = [
    "mkdocs>=1.6",
    "mkdocs-material>=9.5",
    "mkdocstrings[python]>=0.26",
    "mkdocs-jupyter>=0.25",
    "mkdocs-redirects>=1.2,<1.2.3",
    "pymdown-extensions>=10.8",
    "black>=24.0",
    "nbconvert>=7.16",
    "ipykernel",
    "ipywidgets",
]
dlkcat = [
    "torch",
    "rdkit"
]

[project.urls]
Homepage = "https://github.com/qwerty239qwe/pipeGEM"
Documentation = "https://pipegem.readthedocs.io/"

[project.scripts]
pipeGEM = "pipeGEM.cli.cli:main"

[tool.setuptools.package-data]
"pipeGEM.analysis.tasks" = ["task_files/*.json"]
"pipeGEM.cli" = ["configs/*.toml", "configs/*/*.toml"]
"pipeGEM.data" = ["enzyme_data/*", "enzyme_data/human/*", "medium/*"]
"pipeGEM.extensions.DLKcat" = ["precomputed_obj/*"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["pipeGEM*"]

[tool.pytest.ini_options]
norecursedirs = [
    ".git",
    ".pytest_cache",
    ".pytest_state",
    "temp_pytest",
    "temp_pytest_medium",
]
