saved_path = ""

[params]
    name = "local"
    p = 50
    global_on_p = 75
    global_off_p = 25
    global_on_th = nan
    global_off_th = nan

[group]
    group_file_name = nan
    group_name = ""

[plot]
    output_path = nan
    genes = [""]