integrator_name = "GIMME"
saved_path = ""
high_exp = "default"
protected_rxns = []
obj_frac = 0.8
remove_zero_fluxes = false
flux_threshold = 1e-6
max_inconsistency_score = 1e3
return_fluxes = true
keep_context = false