integrator_name = "INIT"
saved_path = ""
protected_rxns = []
eps = 1.0
tol = 1e-6
weight_method = "threshold"

[threshold_kws]
    return_heuristic = false

[precompute]
    [precompute.model]
        cobra_model_path = nan
        model_name_tag = "human1"
    [precompute.tasks]
        task_result_path = nan
    [precompute.threshold]
        threshold_result_path = nan
        type = "rFASTCORMICS"
    [precompute.rxn_scaling_factor]
        file_path = nan